### ISSUE TITLE
Pre-built docker image

### ISSUE THREAD

**Issue by joshmoore** [glencoesoftware/omero-ms-thumbnail#17]
omero-ms-zarr now has a working GitHub Action to DockerHub setup. If there is no objection, I'll reproduce that configuration here.

see:
 - https://github.com/ome/omero-ms-zarr/blob/master/.github/workflows/dockerpublish.yml
 - https://github.com/ome/omero-ms-zarr/blob/master/Dockerfile

**Comment by chris-allan** [comment]
No objections at all.

**Comment by joshmoore** [comment]
Image now up on Docker Hub: https://hub.docker.com/r/openmicroscopy/omero-ms-thumbnail/tags

cc: @manics
